# Generated by Django 3.0.6 on 2020-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='updated_at',
            field=models.DateField(blank=True),
        ),
    ]
